package com.trafficlabel.service;

import java.util.List;

import com.trafficlabel.dto.Person;

public class PersonProvider {

    public static List<Person> getAllPersons() {
        return List.of(
            Person.builder()
                .id(1)
                .age(28)
                .firstName("John")
                .lastName("Smith")
                .phoneNumber("0123242334")
                .address(Person.Address.builder()
                    .address1("21 Somewhere")
                    .city("Best City")
                    .postcode("AB12ER")
                    .build())
                .build(),
            Person.builder()
                .id(2)
                .age(31)
                .firstName("Mark")
                .lastName("Poke")
                .phoneNumber("0223242334")
                .address(Person.Address.builder()
                    .address1("24 Somewhere")
                    .city("Average City")
                    .postcode("AZ12ER")
                    .build())
                .build(),
            Person.builder()
                .id(3)
                .age(22)
                .firstName("Ellie")
                .lastName("May")
                .phoneNumber("0323242334")
                .address(Person.Address.builder()
                    .address1("45 Somewhere")
                    .city("Best City")
                    .postcode("AX12ER")
                    .build())
                .build(),
            Person.builder()
                .id(4)
                .age(19)
                .firstName("Tom")
                .lastName("Sander")
                .phoneNumber("0423242334")
                .address(Person.Address.builder()
                    .address1("2 Elsewhere")
                    .city("Average City")
                    .postcode("AK12ER")
                    .build())
                .build(),
            Person.builder()
                .id(5)
                .age(45)
                .firstName("Christine")
                .lastName("Black")
                .phoneNumber("0723242334")
                .address(Person.Address.builder()
                    .address1("56 Elsewhere")
                    .city("Average City")
                    .postcode("AB12EV")
                    .build())
                .build(),
            Person.builder()
                .id(6)
                .age(37)
                .firstName("Chris")
                .lastName("White")
                .phoneNumber("0883242334")
                .address(Person.Address.builder()
                    .address1("10 Cool Road")
                    .city("Best City")
                    .postcode("ACC2ER")
                    .build())
                .build(),
            Person.builder()
                .id(7)
                .age(35)
                .firstName("Ann")
                .lastName("Young")
                .phoneNumber("0777242334")
                .address(Person.Address.builder()
                    .address1("12 Cool Road")
                    .city("Best City")
                    .postcode("ACC2ER")
                    .build())
                .build(),
            Person.builder()
                .id(8)
                .age(54)
                .firstName("Phil")
                .lastName("Smith")
                .phoneNumber("0223242334")
                .address(Person.Address.builder()
                    .address1("3 Best Road")
                    .city("Worst City")
                    .postcode("AB12XX")
                    .build())
                .build(),
            Person.builder()
                .id(9)
                .age(null)
                .firstName("Amy")
                .lastName("Rose")
                .phoneNumber("0333242334")
                .address(Person.Address.builder()
                    .address1("33 Quite Road")
                    .city("Nice City")
                    .postcode("EB12XX")
                    .build())
                .build()
        );
    }

}
